//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PL_MVC.ServicePoliza {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Result", Namespace="http://schemas.datacontract.org/2004/07/SL_WCF")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(object[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ML.Poliza))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ML.SubPoliza))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ML.Usuario))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ML.Direccion))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ML.Rol))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Exception))]
    public partial class Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CorrectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Exception ExField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object ObjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object[] ObjectsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Correct {
            get {
                return this.CorrectField;
            }
            set {
                if ((this.CorrectField.Equals(value) != true)) {
                    this.CorrectField = value;
                    this.RaisePropertyChanged("Correct");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Exception Ex {
            get {
                return this.ExField;
            }
            set {
                if ((object.ReferenceEquals(this.ExField, value) != true)) {
                    this.ExField = value;
                    this.RaisePropertyChanged("Ex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Object {
            get {
                return this.ObjectField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjectField, value) != true)) {
                    this.ObjectField = value;
                    this.RaisePropertyChanged("Object");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object[] Objects {
            get {
                return this.ObjectsField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjectsField, value) != true)) {
                    this.ObjectsField = value;
                    this.RaisePropertyChanged("Objects");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicePoliza.IPoliza")]
    public interface IPoliza {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPoliza/Add", ReplyAction="http://tempuri.org/IPoliza/AddResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.SubPoliza))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Usuario))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Direccion))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Rol))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PL_MVC.ServicePoliza.Result))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        PL_MVC.ServicePoliza.Result Add(ML.Poliza poliza);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPoliza/Add", ReplyAction="http://tempuri.org/IPoliza/AddResponse")]
        System.Threading.Tasks.Task<PL_MVC.ServicePoliza.Result> AddAsync(ML.Poliza poliza);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPoliza/Update", ReplyAction="http://tempuri.org/IPoliza/UpdateResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.SubPoliza))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Usuario))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Direccion))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Rol))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PL_MVC.ServicePoliza.Result))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        PL_MVC.ServicePoliza.Result Update(ML.Poliza poliza);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPoliza/Update", ReplyAction="http://tempuri.org/IPoliza/UpdateResponse")]
        System.Threading.Tasks.Task<PL_MVC.ServicePoliza.Result> UpdateAsync(ML.Poliza poliza);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPoliza/Delete", ReplyAction="http://tempuri.org/IPoliza/DeleteResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.SubPoliza))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Usuario))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Direccion))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Rol))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PL_MVC.ServicePoliza.Result))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        PL_MVC.ServicePoliza.Result Delete(ML.Poliza poliza);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPoliza/Delete", ReplyAction="http://tempuri.org/IPoliza/DeleteResponse")]
        System.Threading.Tasks.Task<PL_MVC.ServicePoliza.Result> DeleteAsync(ML.Poliza poliza);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPoliza/GetAll", ReplyAction="http://tempuri.org/IPoliza/GetAllResponse")]
        PL_MVC.ServicePoliza.Result GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPoliza/GetAll", ReplyAction="http://tempuri.org/IPoliza/GetAllResponse")]
        System.Threading.Tasks.Task<PL_MVC.ServicePoliza.Result> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPoliza/GetById", ReplyAction="http://tempuri.org/IPoliza/GetByIdResponse")]
        PL_MVC.ServicePoliza.Result GetById(int IdPoliza);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPoliza/GetById", ReplyAction="http://tempuri.org/IPoliza/GetByIdResponse")]
        System.Threading.Tasks.Task<PL_MVC.ServicePoliza.Result> GetByIdAsync(int IdPoliza);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPolizaChannel : PL_MVC.ServicePoliza.IPoliza, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PolizaClient : System.ServiceModel.ClientBase<PL_MVC.ServicePoliza.IPoliza>, PL_MVC.ServicePoliza.IPoliza {
        
        public PolizaClient() {
        }
        
        public PolizaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PolizaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PolizaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PolizaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PL_MVC.ServicePoliza.Result Add(ML.Poliza poliza) {
            return base.Channel.Add(poliza);
        }
        
        public System.Threading.Tasks.Task<PL_MVC.ServicePoliza.Result> AddAsync(ML.Poliza poliza) {
            return base.Channel.AddAsync(poliza);
        }
        
        public PL_MVC.ServicePoliza.Result Update(ML.Poliza poliza) {
            return base.Channel.Update(poliza);
        }
        
        public System.Threading.Tasks.Task<PL_MVC.ServicePoliza.Result> UpdateAsync(ML.Poliza poliza) {
            return base.Channel.UpdateAsync(poliza);
        }
        
        public PL_MVC.ServicePoliza.Result Delete(ML.Poliza poliza) {
            return base.Channel.Delete(poliza);
        }
        
        public System.Threading.Tasks.Task<PL_MVC.ServicePoliza.Result> DeleteAsync(ML.Poliza poliza) {
            return base.Channel.DeleteAsync(poliza);
        }
        
        public PL_MVC.ServicePoliza.Result GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<PL_MVC.ServicePoliza.Result> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public PL_MVC.ServicePoliza.Result GetById(int IdPoliza) {
            return base.Channel.GetById(IdPoliza);
        }
        
        public System.Threading.Tasks.Task<PL_MVC.ServicePoliza.Result> GetByIdAsync(int IdPoliza) {
            return base.Channel.GetByIdAsync(IdPoliza);
        }
    }
}
